name: 'Yarn Cache'
runs:
  using: 'composite'
  steps:
    - name: Get yarn cache folder
      id: get-yarn-cache-folder
      shell: bash
      run: echo "::set-output name=path::$(yarn config get cacheFolder)"
    - name: Cache modules
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-yarn-cache-folder.outputs.path }}
        key: yarn-cache-folder-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-cache-folder-os-${{ runner.os }}-node-${{ env.NODE_VERSION }}-
          yarn-cache-folder-os-${{ runner.os }}-
