// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.migration_lock */
export type MigrationLockIndex = number & { __brand: 'MigrationLockIndex' }

/** Represents the table public.migration_lock */
export default interface MigrationLock {
  index: MigrationLockIndex

  is_locked: number | null
}

/** Represents the initializer for the table public.migration_lock */
export interface MigrationLockInitializer {
  /** Default value: nextval('migration_lock_index_seq'::regclass) */
  index?: MigrationLockIndex

  is_locked?: number | null
}

/** Represents the mutator for the table public.migration_lock */
export interface MigrationLockMutator {
  index?: MigrationLockIndex

  is_locked?: number | null
}
