// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.migration */
export type MigrationId = number & { __brand: 'MigrationId' }

/** Represents the table public.migration */
export default interface Migration {
  id: MigrationId

  name: string | null

  batch: number | null

  migration_time: Date | null
}

/** Represents the initializer for the table public.migration */
export interface MigrationInitializer {
  /** Default value: nextval('migration_id_seq'::regclass) */
  id?: MigrationId

  name?: string | null

  batch?: number | null

  migration_time?: Date | null
}

/** Represents the mutator for the table public.migration */
export interface MigrationMutator {
  id?: MigrationId

  name?: string | null

  batch?: number | null

  migration_time?: Date | null
}
