// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.person */
export type PersonId = number & { __brand: 'PersonId' }

/** Represents the table public.person */
export default interface Person {
  id: PersonId

  name: string

  email: string
}

/** Represents the initializer for the table public.person */
export interface PersonInitializer {
  id?: PersonId

  name: string

  email: string
}

/** Represents the mutator for the table public.person */
export interface PersonMutator {
  id?: PersonId

  name?: string

  email?: string
}
